package util

var HofSlayerBosses = []BossInfo{
	{BossName: "sire", ImageLink: "https://i.imgur.com/GhbmqEB.png"},
	{BossName: "hydra", ImageLink: "https://i.imgur.com/25GU0Ph.png"},
	{BossName: "cerberus", ImageLink: "https://i.imgur.com/UoxGuQi.png"},
	{BossName: "grotesqueguardians", ImageLink: "https://i.imgur.com/M7ylVBZ.png"},
	{BossName: "kraken", ImageLink: "https://i.imgur.com/Q6EbJb1.png"},
	{BossName: "smokedevil", ImageLink: "https://i.imgur.com/2AYntQ5.png"},
}

var HofGWDBosses = []BossInfo{
	{BossName: "commanderzilyana", ImageLink: "https://i.imgur.com/aNm4Ydd.png"},
	{BossName: "kreearra", ImageLink: "https://i.imgur.com/lX8SfgN.png"},
	{BossName: "kriltsutsaroth", ImageLink: "https://i.imgur.com/hh8cMvp.png"},
	{BossName: "nex", ImageLink: "https://i.imgur.com/pqiVQBC.png"},
	{BossName: "generalgraardor", ImageLink: "https://i.imgur.com/hljv9ZW.png"},
}

var HofWildyBosses = []BossInfo{
	{BossName: "artio", ImageLink: "https://i.imgur.com/bw6zLpU.png"},
	{BossName: "callisto", ImageLink: "https://i.imgur.com/bw6zLpU.png"},
	{BossName: "calvarion", ImageLink: "https://i.imgur.com/v3KX75y.png"},
	{BossName: "vetion", ImageLink: "https://i.imgur.com/v3KX75y.png"},
	{BossName: "spindel", ImageLink: "https://i.imgur.com/4zknWSX.png"},
	{BossName: "venenatis", ImageLink: "https://i.imgur.com/4zknWSX.png"},
	{BossName: "chaoselemental", ImageLink: "https://i.imgur.com/YAvIpbm.png"},
	{BossName: "chaosfanatic", ImageLink: "https://i.imgur.com/azV2sD1.png"},
	{BossName: "crazyarchaeologist", ImageLink: "https://i.imgur.com/23LXv53.png"},
	{BossName: "scorpia", ImageLink: "https://i.imgur.com/9aaguxB.png"},
}

var HofOtherBosses = []BossInfo{
	{BossName: "corporealbeast", ImageLink: "https://i.imgur.com/zEDN4Pf.png"},
	{BossName: "prime", ImageLink: "https://i.imgur.com/kJBtqHB.png"},
	{BossName: "rexbro", ImageLink: "https://i.imgur.com/PvlGWFZ.png"},
	{BossName: "supreme", ImageLink: "https://i.imgur.com/BOgkBuD.png"},
	{BossName: "gauntlet", ImageLink: "https://i.imgur.com/weiHWnz.png"},
	{BossName: "gauntlethard", ImageLink: "https://i.imgur.com/xzW4TGR.png"},
	{BossName: "giantmole", ImageLink: "https://i.imgur.com/coKk2pr.png"},
	{BossName: "jad", ImageLink: "https://i.imgur.com/H9aO1Ot.png"},
	{BossName: "zuk", ImageLink: "https://i.imgur.com/mKstHza.png"},
	{BossName: "kq", ImageLink: "https://i.imgur.com/ZuaFoBR.png"},
	{BossName: "kbd", ImageLink: "https://i.imgur.com/r5vkw1s.png"},
	{BossName: "sarachnis", ImageLink: "https://i.imgur.com/98THH8O.png"},
	{BossName: "skotizo", ImageLink: "https://i.imgur.com/YUcQu4d.png"},
	{BossName: "muspah", ImageLink: "https://i.imgur.com/sW2cLQ2.png"},
	{BossName: "vorkath", ImageLink: "https://i.imgur.com/6biF3P2.png"},
	{BossName: "nightmare", ImageLink: "https://i.imgur.com/4aDkxms.png"},
	{BossName: "phosanis", ImageLink: "https://i.imgur.com/4aDkxms.png"},
	{BossName: "zulrah", ImageLink: "https://i.imgur.com/tPllWNF.png"},
}

var HofMiscBosses = []BossInfo{
	{BossName: "barrows", ImageLink: "https://i.imgur.com/ajoK20v.png"},
	{BossName: "hespori", ImageLink: "https://i.imgur.com/b0qYGHS.png"},
	{BossName: "mimic", ImageLink: "https://i.imgur.com/jC7yTC3.png"},
	{BossName: "obor", ImageLink: "https://i.imgur.com/dwLvSbR.png"},
	{BossName: "bryophyta", ImageLink: "https://i.imgur.com/3cdyp4X.png"},
	{BossName: "derangedarchaeologist", ImageLink: "https://i.imgur.com/cnHpevF.png"},
	{BossName: "wintertodt", ImageLink: "https://i.imgur.com/6oFef2Y.png"},
	{BossName: "zalcano", ImageLink: "https://i.imgur.com/edN11Nf.png"},
	{BossName: "rift", ImageLink: "https://i.imgur.com/MOiyXeH.png"},
}

var HofDT2Bosses = []BossInfo{
	{BossName: "duke", ImageLink: "https://i.imgur.com/RYPmrXy.png"},
	{BossName: "leviathan", ImageLink: "https://i.imgur.com/mEQRq5c.png"},
	{BossName: "whisperer", ImageLink: "https://i.imgur.com/cFGWb6Y.png"},
	{BossName: "vardorvis", ImageLink: "https://i.imgur.com/WMPuShZ.png"},
}

var HofRaidsBosses = []BossInfo{
	{BossName: "cox", ImageLink: "https://i.imgur.com/gxdWXtH.png"},
	{BossName: "coxcm", ImageLink: "https://i.imgur.com/gxdWXtH.png"},
	{BossName: "tob", ImageLink: "https://i.imgur.com/pW1sJAQ.png"},
	{BossName: "tobcm", ImageLink: "https://i.imgur.com/pW1sJAQ.png"},
	{BossName: "toa", ImageLink: "https://i.imgur.com/2GvzqGw.png"},
	{BossName: "toae", ImageLink: "https://i.imgur.com/2GvzqGw.png"},
}

var HofPVPBosses = []BossInfo{
	{BossName: "bhh", ImageLink: "https://i.imgur.com/zSQhlWk.png"},
	{BossName: "bhr", ImageLink: "https://i.imgur.com/Y3Sga7t.png"},
	{BossName: "lms", ImageLink: "https://i.imgur.com/rzW7ZXx.png"},
	{BossName: "arena", ImageLink: "https://i.imgur.com/uNP6Ggu.png"},
	{BossName: "zeal", ImageLink: "https://i.imgur.com/Ws7HvKL.png"},
}

var HofCluesBosses = []BossInfo{
	{BossName: "cluebeginner", ImageLink: "https://i.imgur.com/fUmzJkW.png"},
	{BossName: "clueeasy", ImageLink: "https://i.imgur.com/phnSCHj.png"},
	{BossName: "cluemedium", ImageLink: "https://i.imgur.com/t5iH8Xa.png"},
	{BossName: "cluehard", ImageLink: "https://i.imgur.com/a0xwcGI.png"},
	{BossName: "clueelite", ImageLink: "https://i.imgur.com/ibNRk3G.png"},
	{BossName: "cluemaster", ImageLink: "https://i.imgur.com/12rCLVv.png"},
	{BossName: "clueall", ImageLink: "https://i.imgur.com/wX3Ei7U.png"},
}

var HofSpeedTzhaar = []BossInfo{
	{BossName: "TzHaar Fight Cave"},
	{BossName: "Inferno"},
}

var HofSpeedSlayer = []BossInfo{
	{BossName: "Alchemical Hydra"},
	{BossName: "Grotesque Guardians"},
}

var HofSpeedNightmare = []BossInfo{
	{BossName: "The Nightmare Solo"},
	{BossName: "The Nightmare 2"},
	{BossName: "The Nightmare 3"},
	{BossName: "The Nightmare 4"},
	{BossName: "The Nightmare 5"},
	{BossName: "The Nightmare 6+"},
	{BossName: "Phosani's Nightmare"},
}

var HofSpeedNex = []BossInfo{
	{BossName: "Nex", ImageLink: "https://i.imgur.com/hnw9ki8.png"},
}

var HofSpeedSolo = []BossInfo{
	{BossName: "Fragment of Seren"},
	{BossName: "Galvek"},
	{BossName: "The Gauntlet"},
	{BossName: "The Corrupted Gauntlet"},
	{BossName: "Hespori"},
	{BossName: "Phantom Muspah"},
	{BossName: "Vorkath"},
	{BossName: "Zulrah"},
	{BossName: "Tempoross"},
}

var HofSpeedCox = []BossInfo{
	{BossName: "Chambers of Xeric Solo"},
	{BossName: "Chambers of Xeric 2"},
	{BossName: "Chambers of Xeric 3"},
	{BossName: "Chambers of Xeric 4"},
	{BossName: "Chambers of Xeric 5"},
	{BossName: "Chambers of Xeric 6"},
	{BossName: "Chambers of Xeric 7"},
	{BossName: "Chambers of Xeric 8"},
	{BossName: "Chambers of Xeric 9"},
	{BossName: "Chambers of Xeric 10"},
	{BossName: "Chambers of Xeric 11-15"},
	{BossName: "Chambers of Xeric 16-23"},
	{BossName: "Chambers of Xeric 24+"},
	{BossName: "Chambers of Xeric - Challenge mode Solo"},
	{BossName: "Chambers of Xeric - Challenge mode 2"},
	{BossName: "Chambers of Xeric - Challenge mode 3"},
	{BossName: "Chambers of Xeric - Challenge mode 4"},
	{BossName: "Chambers of Xeric - Challenge mode 5"},
	{BossName: "Chambers of Xeric - Challenge mode 6"},
	{BossName: "Chambers of Xeric - Challenge mode 7"},
	{BossName: "Chambers of Xeric - Challenge mode 8"},
	{BossName: "Chambers of Xeric - Challenge mode 9"},
	{BossName: "Chambers of Xeric - Challenge mode 10"},
}

var HofSpeedTob = []BossInfo{
	{BossName: "Theatre of Blood - Entry Room 1"},
	{BossName: "Theatre of Blood - Entry Room 2"},
	{BossName: "Theatre of Blood - Entry Room 3"},
	{BossName: "Theatre of Blood - Entry Room 4"},
	{BossName: "Theatre of Blood - Entry Overall 1"},
	{BossName: "Theatre of Blood - Entry Overall 2"},
	{BossName: "Theatre of Blood - Entry Overall 3"},
	{BossName: "Theatre of Blood - Entry Overall 4"},
	{BossName: "Theatre of Blood Room 2"},
	{BossName: "Theatre of Blood Room 3"},
	{BossName: "Theatre of Blood Room 4"},
	{BossName: "Theatre of Blood Room 5"},
	{BossName: "Theatre of Blood Overall 2"},
	{BossName: "Theatre of Blood Overall 3"},
	{BossName: "Theatre of Blood Overall 4"},
	{BossName: "Theatre of Blood Overall 5"},
	{BossName: "Theatre of Blood - Hard Room 3"},
	{BossName: "Theatre of Blood - Hard Room 4"},
	{BossName: "Theatre of Blood - Hard Room 5"},
	{BossName: "Theatre of Blood - Hard Overall 3"},
	{BossName: "Theatre of Blood - Hard Overall 4"},
	{BossName: "Theatre of Blood - Hard Overall 5"},
}

var HofSpeedToa = []BossInfo{
	{BossName: "Tombs of Amascut - Entry Room Solo"},
	{BossName: "Tombs of Amascut - Entry Room 2"},
	{BossName: "Tombs of Amascut - Entry Room 4"},
	{BossName: "Tombs of Amascut - Entry Room 6"},
	{BossName: "Tombs of Amascut - Entry Overall Solo"},
	{BossName: "Tombs of Amascut - Entry Overall 2"},
	{BossName: "Tombs of Amascut - Entry Overall 4"},
	{BossName: "Tombs of Amascut - Entry Overall 6"},
	{BossName: "Tombs of Amascut Room Solo"},
	{BossName: "Tombs of Amascut Room 2"},
	{BossName: "Tombs of Amascut Room 3"},
	{BossName: "Tombs of Amascut Room 4"},
	{BossName: "Tombs of Amascut Room 5"},
	{BossName: "Tombs of Amascut Room 6"},
	{BossName: "Tombs of Amascut Room 7"},
	{BossName: "Tombs of Amascut Overall Solo"},
	{BossName: "Tombs of Amascut Overall 2"},
	{BossName: "Tombs of Amascut Overall 3"},
	{BossName: "Tombs of Amascut Overall 4"},
	{BossName: "Tombs of Amascut Overall 5"},
	{BossName: "Tombs of Amascut Overall 6"},
	{BossName: "Tombs of Amascut Overall 7"},
	{BossName: "Tombs of Amascut Expert Room Solo"},
	{BossName: "Tombs of Amascut Expert Room 2"},
	{BossName: "Tombs of Amascut Expert Room 3"},
	{BossName: "Tombs of Amascut Expert Room 4"},
	{BossName: "Tombs of Amascut Expert Room 5"},
	{BossName: "Tombs of Amascut Expert Room 6"},
	{BossName: "Tombs of Amascut Expert Room 7"},
	{BossName: "Tombs of Amascut Expert Room 8"},
	{BossName: "Tombs of Amascut Expert Overall Solo"},
	{BossName: "Tombs of Amascut Expert Overall 2"},
	{BossName: "Tombs of Amascut Expert Overall 3"},
	{BossName: "Tombs of Amascut Expert Overall 4"},
	{BossName: "Tombs of Amascut Expert Overall 5"},
	{BossName: "Tombs of Amascut Expert Overall 6"},
	{BossName: "Tombs of Amascut Expert Overall 7"},
	{BossName: "Tombs of Amascut Expert Overall 8"},
}

var HofSpeedAgility = []BossInfo{
	{BossName: "Hallowed Sepulchre"},
	{BossName: "Prifddinas Agility Course"},
}

var SpeedBossNames = map[string]struct{}{
	"TzHaar Fight Cave":                       {},
	"Inferno":                                 {},
	"Alchemical Hydra":                        {},
	"Fragment of Seren":                       {},
	"Galvek":                                  {},
	"The Gauntlet":                            {},
	"The Corrupted Gauntlet":                  {},
	"Grotesque Guardians":                     {},
	"Hespori":                                 {},
	"Phantom Muspah":                          {},
	"Nex":                                     {},
	"The Nightmare Solo":                      {},
	"The Nightmare 2":                         {},
	"The Nightmare 3":                         {},
	"The Nightmare 4":                         {},
	"The Nightmare 5":                         {},
	"The Nightmare 6+":                        {},
	"Phosani's Nightmare":                     {},
	"Vorkath":                                 {},
	"Zulrah":                                  {},
	"Tempoross":                               {},
	"Chambers of Xeric Solo":                  {},
	"Chambers of Xeric 2":                     {},
	"Chambers of Xeric 3":                     {},
	"Chambers of Xeric 4":                     {},
	"Chambers of Xeric 5":                     {},
	"Chambers of Xeric 6":                     {},
	"Chambers of Xeric 7":                     {},
	"Chambers of Xeric 8":                     {},
	"Chambers of Xeric 9":                     {},
	"Chambers of Xeric 10":                    {},
	"Chambers of Xeric 11-15":                 {},
	"Chambers of Xeric 16-23":                 {},
	"Chambers of Xeric 24+":                   {},
	"Chambers of Xeric - Challenge mode Solo": {},
	"Chambers of Xeric - Challenge mode 2":    {},
	"Chambers of Xeric - Challenge mode 3":    {},
	"Chambers of Xeric - Challenge mode 4":    {},
	"Chambers of Xeric - Challenge mode 5":    {},
	"Chambers of Xeric - Challenge mode 6":    {},
	"Chambers of Xeric - Challenge mode 7":    {},
	"Chambers of Xeric - Challenge mode 8":    {},
	"Chambers of Xeric - Challenge mode 9":    {},
	"Chambers of Xeric - Challenge mode 10":   {},
	"Theatre of Blood - Entry Room 1":         {},
	"Theatre of Blood - Entry Room 2":         {},
	"Theatre of Blood - Entry Room 3":         {},
	"Theatre of Blood - Entry Room 4":         {},
	"Theatre of Blood - Entry Overall 1":      {},
	"Theatre of Blood - Entry Overall 2":      {},
	"Theatre of Blood - Entry Overall 3":      {},
	"Theatre of Blood - Entry Overall 4":      {},
	"Theatre of Blood Room 2":                 {},
	"Theatre of Blood Room 3":                 {},
	"Theatre of Blood Room 4":                 {},
	"Theatre of Blood Room 5":                 {},
	"Theatre of Blood Overall 2":              {},
	"Theatre of Blood Overall 3":              {},
	"Theatre of Blood Overall 4":              {},
	"Theatre of Blood Overall 5":              {},
	"Theatre of Blood - Hard Room 3":          {},
	"Theatre of Blood - Hard Room 4":          {},
	"Theatre of Blood - Hard Room 5":          {},
	"Theatre of Blood - Hard Overall 3":       {},
	"Theatre of Blood - Hard Overall 4":       {},
	"Theatre of Blood - Hard Overall 5":       {},
	"Tombs of Amascut - Entry Room Solo":      {},
	"Tombs of Amascut - Entry Room 2":         {},
	"Tombs of Amascut - Entry Room 4":         {},
	"Tombs of Amascut - Entry Room 6":         {},
	"Tombs of Amascut - Entry Overall Solo":   {},
	"Tombs of Amascut - Entry Overall 2":      {},
	"Tombs of Amascut - Entry Overall 4":      {},
	"Tombs of Amascut - Entry Overall 6":      {},
	"Tombs of Amascut Room Solo":              {},
	"Tombs of Amascut Room 2":                 {},
	"Tombs of Amascut Room 3":                 {},
	"Tombs of Amascut Room 4":                 {},
	"Tombs of Amascut Room 5":                 {},
	"Tombs of Amascut Room 6":                 {},
	"Tombs of Amascut Room 7":                 {},
	"Tombs of Amascut Overall Solo":           {},
	"Tombs of Amascut Overall 2":              {},
	"Tombs of Amascut Overall 3":              {},
	"Tombs of Amascut Overall 4":              {},
	"Tombs of Amascut Overall 5":              {},
	"Tombs of Amascut Overall 6":              {},
	"Tombs of Amascut Overall 7":              {},
	"Tombs of Amascut - Expert Room Solo":     {},
	"Tombs of Amascut - Expert Room 2":        {},
	"Tombs of Amascut - Expert Room 3":        {},
	"Tombs of Amascut - Expert Room 4":        {},
	"Tombs of Amascut - Expert Room 5":        {},
	"Tombs of Amascut - Expert Room 6":        {},
	"Tombs of Amascut - Expert Room 7":        {},
	"Tombs of Amascut - Expert Room 8":        {},
	"Tombs of Amascut - Expert Overall Solo":  {},
	"Tombs of Amascut - Expert Overall 2":     {},
	"Tombs of Amascut - Expert Overall 3":     {},
	"Tombs of Amascut - Expert Overall 4":     {},
	"Tombs of Amascut - Expert Overall 5":     {},
	"Tombs of Amascut - Expert Overall 6":     {},
	"Tombs of Amascut - Expert Overall 7":     {},
	"Tombs of Amascut - Expert Overall 8":     {},
	"Hallowed Sepulchre":                      {},
	"Prifddinas Agility Course":               {},
}

var LootLogClanPoint = map[string]struct{}{

	// Cox
	"Dexterous prayer scroll":      {},
	"Arcane prayer scroll":         {},
	"Twisted buckler":              {},
	"Dragon hunter crossbow":       {},
	"Dinh's bulwark":               {},
	"Ancestral hat":                {},
	"Ancestral robe top":           {},
	"Ancestral robe bottom":        {},
	"Dragon claws":                 {},
	"Elder maul":                   {},
	"Kodai insignia":               {},
	"Twisted bow":                  {},
	"Twisted ancestral colour kit": {},
	"Metamorphic dust":             {},

	// Tob
	"Avernic defender hilt":         {},
	"Ghrazi rapier":                 {},
	"Sanguinesti staff":             {},
	"Sanguinesti staff (uncharged)": {},
	"Justiciar faceguard":           {},
	"Justiciar chestguard":          {},
	"Justiciar legguards":           {},
	"Scythe of vitur":               {},
	"Scythe of vitur (uncharged)":   {},
	"Holy ornament kit":             {},
	"Sanguine ornament kit":         {},
	"Sanguine dust":                 {},

	// Toa
	"Osmumten's fang":              {},
	"Lightbearer":                  {},
	"Elidinis' ward":               {},
	"Masori mask":                  {},
	"Masori body":                  {},
	"Masori chaps":                 {},
	"Tumeken's shadow":             {},
	"Tumeken's shadow (uncharged)": {},
	"Thread of elidinis":           {},
	"Eye of the corruptor":         {},
	"Jewel of the sun":             {},
	"Breach of the scarab":         {},

	// Clue mega rares
	"Gilded full helm":             {},
	"Gilded platebody":             {},
	"Gilded platelegs":             {},
	"Gilded plateskirt":            {},
	"Gilded kiteshield":            {},
	"Gilded med helm":              {},
	"Gilded chainbody":             {},
	"Gilded sq shield":             {},
	"Gilded 2h sword":              {},
	"Gilded spear":                 {},
	"Gilded hasta":                 {},
	"3rd age full helmet":          {},
	"3rd age platebody":            {},
	"3rd age platelegs":            {},
	"3rd age plateskirt":           {},
	"3rd age kiteshield":           {},
	"3rd age range coif":           {},
	"3rd age range top":            {},
	"3rd age range legs":           {},
	"3rd age vambraces":            {},
	"3rd age mage hat":             {},
	"3rd age robe top":             {},
	"3rd age robe":                 {},
	"3rd age amulet":               {},
	"Gilded scimitar":              {},
	"Gilded boots":                 {},
	"Gilded coif":                  {},
	"Gilded d'hide vambraces":      {},
	"Gilded d'hide body":           {},
	"Gilded d'hide chaps":          {},
	"Gilded pickaxe":               {},
	"Gilded axe":                   {},
	"Gilded spade":                 {},
	"3rd age longsword":            {},
	"3rd age wand":                 {},
	"3rd age cloak":                {},
	"3rd age bow":                  {},
	"Bucket helm (g)":              {},
	"Ring of coins":                {},
	"3rd age druidic robe top":     {},
	"3rd age druidic robe bottoms": {},
	"3rd age druidic cloak":        {},
	"3rd age druidic staff":        {},
	"3rd age pickaxe":              {},
	"3rd age axe":                  {},

	// Slayer
	"Hydra's claw":          {},
	"Hydra leather":         {},
	"Primordial crystal":    {},
	"Pegasian crystal":      {},
	"Eternal crystal":       {},
	"Occult necklace":       {},
	"Dragon harpoon":        {},
	"Black tourmaline core": {},
	"Smoke battlestaff":     {},
	"Mist battlestaff":      {},
	"Dust battlestaff":      {},
	"Imbued heart":          {},
	"Eternal gem":           {},
	"Zenyte shard":          {},
	"Monkey tail":           {},
	"Heavy frame":           {},
	"Light frame":           {},
	"Ballista spring":       {},
	"Ballista limbs":        {},

	// Wilderness
	"Claws of callisto":       {},
	"Tyrannical ring":         {},
	"Voidwaker hilt":          {},
	"Dragon pickaxe":          {},
	"Skull of vet'ion":        {},
	"Ring of the gods":        {},
	"Voidwaker blade":         {},
	"Fangs of venenatis":      {},
	"Treasonous ring":         {},
	"Voidwaker gem":           {},
	"Amulet of avarice":       {},
	"Craw's bow":              {},
	"Craw's bow (u)":          {},
	"Thammaron's sceptre":     {},
	"Thammaron's sceptre (u)": {},
	"Viggora's chainmace":     {},
	"Viggora's chainmace (u)": {},
	"Ancient crystal":         {},
	"Ancient relic":           {},
	"Ancient effigy":          {},
	"Ancient medallion":       {},
	"Ancient statuette":       {},
	"Ancient totem":           {},
	"Ancient emblem":          {},
	"Dagon'hai robe top":      {},
	"Dagon'hai hat":           {},
	"Dagon'hai robe bottom":   {},

	// DT2
	"Chromium ingot":             {},
	"Ultor vestige":              {},
	"Executioner's axe head":     {},
	"Virtus mask":                {},
	"Virtus robe top":            {},
	"Virtus robe bottom":         {},
	"Ancient blood ornament kit": {},
	"Bellator vestige":           {},
	"Siren's staff":              {},
	"Venator vestige":            {},
	"Leviathan's lure":           {},
	"Magus vestige":              {},
	"Eye of the duke":            {},

	// Other
	"Bryophyta's essence":     {},
	"Hill giant club":         {},
	"Dragon full helm":        {},
	"Infernal cape":           {},
	"Wyvern visage":           {},
	"Skeletal visage":         {},
	"Draconic visage":         {},
	"Dragon warhammer":        {},
	"Amulet of eternal glory": {},
	"Evil chicken head":       {},
	"Evil chicken wings":      {},
	"Evil chicken legs":       {},
	"Evil chicken feet":       {},
	"Abyssal lantern":         {},
	"Abyssal needle":          {},
	"Abyssal green dye":       {},
	"Abyssal blue dye":        {},
	"Abyssal red dye":         {},

	// Zulrah
	"Tanzanite mutagen": {},
	"Magma mutagen":     {},
	"Uncut onyx":        {},
	"Serpentine visage": {},
	"Magic fang":        {},
	"Tanzanite fang":    {},

	// Gauntlet
	"Enhanced crystal weapon seed": {},
	"Crystal armour seed":          {},

	// Godwars
	"Armadyl helmet":            {},
	"Armadyl chestplate":        {},
	"Armadyl chainskirt":        {},
	"Armadyl hilt":              {},
	"Bandos chestplate":         {},
	"Bandos tassets":            {},
	"Bandos boots":              {},
	"Bandos hilt":               {},
	"Saradomin sword":           {},
	"Saradomin's light":         {},
	"Armadyl crossbow":          {},
	"Saradomin hilt":            {},
	"Steam battlestaff":         {},
	"Zamorakian spear":          {},
	"Staff of the dead":         {},
	"Zamorak hilt":              {},
	"Zaryte vambraces":          {},
	"Nihil horn":                {},
	"Torva full helm (damaged)": {},
	"Torva platebody (damaged)": {},
	"Torva platelegs (damaged)": {},
	"Torva full helm":           {},
	"Torva platebody":           {},
	"Torva platelegs":           {},
	"Ancient hilt":              {},

	// Nightmare
	"Nightmare staff":         {},
	"Inquisitor's great helm": {},
	"Inquisitor's hauberk":    {},
	"Inquisitor's plateskirt": {},
	"Inquisitor's mace":       {},
	"Eldritch orb":            {},
	"Harmonised orb":          {},
	"Volatile orb":            {},

	// Muspah
	"Venator shard": {},

	// DKS
	"Warrior ring":   {},
	"Berserker ring": {},
	"Dragon axe":     {},
	"Seers ring":     {},
	"Archers ring":   {},

	// Zalcano
	"Zalcano shard":     {},
	"Crystal tool seed": {},

	// Jars
	"Jar of dirt":      {},
	"Jar of swamp":     {},
	"Jar of sand":      {},
	"Jar of souls":     {},
	"Jar of miasma":    {},
	"Jar of darkness":  {},
	"Jar of stone":     {},
	"Jar of decay":     {},
	"Jar of chemicals": {},
	"Jar of eyes":      {},
	"Jar of dreams":    {},
	"Jar of spirits":   {},
	"Jar of smoke":     {},

	// Pets
	"Pet chaos elemental":   {},
	"Pet dagannoth supreme": {},
	"Pet dagannoth prime":   {},
	"Pet dagannoth rex":     {},
	"Pet penance queen":     {},
	"Pet kree'arra":         {},
	"Pet general graardor":  {},
	"Pet zilyana":           {},
	"Pet k'ril tsutsaroth":  {},
	"Baby mole":             {},
	"Prince black dragon":   {},
	"Kalphite princess":     {},
	"Pet smoke devil":       {},
	"Pet kraken":            {},
	"Pet dark core":         {},
	"Pet snakeling":         {},
	"Chompy chick":          {},
	"Venenatis spiderling":  {},
	"Callisto cub":          {},
	"Vet'ion jr.":           {},
	"Scorpia's offspring":   {},
	"Tzrek-jad":             {},
	"Hellpuppy":             {},
	"Abyssal orphan":        {},
	"Heron":                 {},
	"Rock golem":            {},
	"Beaver":                {},
	"Baby chinchompa":       {},
	"Bloodhound":            {},
	"Giant squirrel":        {},
	"Tangleroot":            {},
	"Rift guardian":         {},
	"Rocky":                 {},
	"Phoenix":               {},
	"Olmlet":                {},
	"Skotos":                {},
	"Jal-nib-rek":           {},
	"Herbi":                 {},
	"Noon":                  {},
	"Vorki":                 {},
	"Lil' zik":              {},
	"Ikkle hydra":           {},
	"Sraracha":              {},
	"Youngllef":             {},
	"Smolcano":              {},
	"Little nightmare":      {},
	"Lil' creator":          {},
	"Tiny tempor":           {},
	"Nexling":               {},
	"Abyssal protector":     {},
	"Tumeken's guardian":    {},
	"Muphin":                {},
	"Wisp":                  {},
	"Butch":                 {},
	"Lil'viathan":           {},
	"Baron":                 {},
}
