package util

import "github.com/bwmarrin/discordgo"

// ******************************** KC HOF ********************************

var HofSlayerBosses = []BossInfo{
	{BossName: "Abyssal Sire", ImageLink: "https://i.imgur.com/GhbmqEB.png"},
	{BossName: "Alchemical Hydra", ImageLink: "https://i.imgur.com/25GU0Ph.png"},
	{BossName: "Cerberus", ImageLink: "https://i.imgur.com/UoxGuQi.png"},
	{BossName: "Grotesque Guardians", ImageLink: "https://i.imgur.com/M7ylVBZ.png"},
	{BossName: "Kraken", ImageLink: "https://i.imgur.com/Q6EbJb1.png"},
	{BossName: "Thermonuclear Smoke Devil", ImageLink: "https://i.imgur.com/2AYntQ5.png"},
}

var HofGWDBosses = []BossInfo{
	{BossName: "Commander Zilyana", ImageLink: "https://i.imgur.com/aNm4Ydd.png"},
	{BossName: "KreeArra", ImageLink: "https://i.imgur.com/lX8SfgN.png"},
	{BossName: "Kril Tsutsaroth", ImageLink: "https://i.imgur.com/hh8cMvp.png"},
	{BossName: "Nex", ImageLink: "https://i.imgur.com/pqiVQBC.png"},
	{BossName: "General Graardor", ImageLink: "https://i.imgur.com/hljv9ZW.png"},
}

var HofWildyBosses = []BossInfo{
	{BossName: "Artio", ImageLink: "https://i.imgur.com/bw6zLpU.png"},
	{BossName: "Callisto", ImageLink: "https://i.imgur.com/bw6zLpU.png"},
	{BossName: "Calvarion", ImageLink: "https://i.imgur.com/v3KX75y.png"},
	{BossName: "Vetion", ImageLink: "https://i.imgur.com/v3KX75y.png"},
	{BossName: "Spindel", ImageLink: "https://i.imgur.com/4zknWSX.png"},
	{BossName: "Venenatis", ImageLink: "https://i.imgur.com/4zknWSX.png"},
	{BossName: "Chaos Elemental", ImageLink: "https://i.imgur.com/YAvIpbm.png"},
	{BossName: "Chaos Fanatic", ImageLink: "https://i.imgur.com/azV2sD1.png"},
	{BossName: "Crazy Archaeologist", ImageLink: "https://i.imgur.com/23LXv53.png"},
	{BossName: "Scorpia", ImageLink: "https://i.imgur.com/9aaguxB.png"},
}

var HofOtherBosses = []BossInfo{
	{BossName: "Corporeal Beast", ImageLink: "https://i.imgur.com/zEDN4Pf.png"},
	{BossName: "Dagannoth Prime", ImageLink: "https://i.imgur.com/kJBtqHB.png"},
	{BossName: "Dagannoth Rex", ImageLink: "https://i.imgur.com/PvlGWFZ.png"},
	{BossName: "Dagannoth Supreme", ImageLink: "https://i.imgur.com/BOgkBuD.png"},
	{BossName: "The Gauntlet", ImageLink: "https://i.imgur.com/weiHWnz.png"},
	{BossName: "The Corrupted Gauntlet", ImageLink: "https://i.imgur.com/xzW4TGR.png"},
	{BossName: "Giant Mole", ImageLink: "https://i.imgur.com/coKk2pr.png"},
	{BossName: "TzTok-Jad", ImageLink: "https://i.imgur.com/H9aO1Ot.png"},
	{BossName: "TzKal-Zuk", ImageLink: "https://i.imgur.com/mKstHza.png"},
	{BossName: "Kalphite Queen", ImageLink: "https://i.imgur.com/ZuaFoBR.png"},
	{BossName: "King Black Dragon", ImageLink: "https://i.imgur.com/r5vkw1s.png"},
	{BossName: "Sarachnis", ImageLink: "https://i.imgur.com/98THH8O.png"},
	{BossName: "Skotizo", ImageLink: "https://i.imgur.com/YUcQu4d.png"},
	{BossName: "Phantom Muspah", ImageLink: "https://i.imgur.com/sW2cLQ2.png"},
	{BossName: "Vorkath", ImageLink: "https://i.imgur.com/6biF3P2.png"},
	{BossName: "The Nightmare", ImageLink: "https://i.imgur.com/4aDkxms.png"},
	{BossName: "Phosanis Nightmare", ImageLink: "https://i.imgur.com/4aDkxms.png"},
	{BossName: "Zulrah", ImageLink: "https://i.imgur.com/tPllWNF.png"},
	{BossName: "Scurrius", ImageLink: "https://i.imgur.com/ABNL1Dt.png"},
}

var HofMiscBosses = []BossInfo{
	{BossName: "Barrows Chests", ImageLink: "https://i.imgur.com/ajoK20v.png"},
	{BossName: "Hespori", ImageLink: "https://i.imgur.com/b0qYGHS.png"},
	{BossName: "Mimic", ImageLink: "https://i.imgur.com/jC7yTC3.png"},
	{BossName: "Obor", ImageLink: "https://i.imgur.com/dwLvSbR.png"},
	{BossName: "Bryophyta", ImageLink: "https://i.imgur.com/3cdyp4X.png"},
	{BossName: "Deranged Archaeologist", ImageLink: "https://i.imgur.com/cnHpevF.png"},
	{BossName: "Wintertodt", ImageLink: "https://i.imgur.com/6oFef2Y.png"},
	{BossName: "Zalcano", ImageLink: "https://i.imgur.com/edN11Nf.png"},
	{BossName: "Rift", ImageLink: "https://i.imgur.com/MOiyXeH.png"},
}

var HofDT2Bosses = []BossInfo{
	{BossName: "Duke Sucellus", ImageLink: "https://i.imgur.com/RYPmrXy.png"},
	{BossName: "The Leviathan", ImageLink: "https://i.imgur.com/mEQRq5c.png"},
	{BossName: "The Whisperer", ImageLink: "https://i.imgur.com/cFGWb6Y.png"},
	{BossName: "Vardorvis", ImageLink: "https://i.imgur.com/WMPuShZ.png"},
}

var HofRaidsBosses = []BossInfo{
	{BossName: "Chambers of Xeric", ImageLink: "https://i.imgur.com/gxdWXtH.png"},
	{BossName: "Chambers of Xeric Challenge Mode", ImageLink: "https://i.imgur.com/gxdWXtH.png"},
	{BossName: "Theatre of Blood", ImageLink: "https://i.imgur.com/pW1sJAQ.png"},
	{BossName: "Theatre of Blood Challenge Mode", ImageLink: "https://i.imgur.com/pW1sJAQ.png"},
	{BossName: "Tombs of Amascut", ImageLink: "https://i.imgur.com/2GvzqGw.png"},
	{BossName: "Tombs of Amascut Expert", ImageLink: "https://i.imgur.com/2GvzqGw.png"},
}

var HofPVPBosses = []BossInfo{
	{BossName: "Bounty Hunter Hunter", ImageLink: "https://i.imgur.com/zSQhlWk.png"},
	{BossName: "Bounty Hunter Rogue", ImageLink: "https://i.imgur.com/Y3Sga7t.png"},
	{BossName: "LMS", ImageLink: "https://i.imgur.com/rzW7ZXx.png"},
	{BossName: "PvP Arena", ImageLink: "https://i.imgur.com/uNP6Ggu.png"},
	{BossName: "Soul Wars Zeal", ImageLink: "https://i.imgur.com/Ws7HvKL.png"},
}

var HofCluesBosses = []BossInfo{
	{BossName: "Clue_beginner", ImageLink: "https://i.imgur.com/fUmzJkW.png"},
	{BossName: "Clue_easy", ImageLink: "https://i.imgur.com/phnSCHj.png"},
	{BossName: "Clue_medium", ImageLink: "https://i.imgur.com/t5iH8Xa.png"},
	{BossName: "Clue_hard", ImageLink: "https://i.imgur.com/a0xwcGI.png"},
	{BossName: "Clue_elite", ImageLink: "https://i.imgur.com/ibNRk3G.png"},
	{BossName: "Clue_master", ImageLink: "https://i.imgur.com/12rCLVv.png"},
	{BossName: "Clue_all", ImageLink: "https://i.imgur.com/wX3Ei7U.png"},
}

// ******************************** SPEED HOF ********************************

var HofOrder = []string{"TzHaar Fight Cave",
	"Inferno",
	"Alchemical Hydra",
	"Fragment of Seren",
	"Galvek",
	"Glough",
	"The Gauntlet",
	"The Corrupted Gauntlet",
	"Grotesque Guardians",
	"Hespori",
	"Phantom Muspah",
	"Nex",
	"The Nightmare Solo",
	"The Nightmare 2",
	"The Nightmare 3",
	"The Nightmare 4",
	"The Nightmare 5",
	"The Nightmare 6+",
	"Phosani's Nightmare",
	"Vorkath",
	"Zulrah",
	"Tempoross",
	"Chambers of Xeric Solo",
	"Chambers of Xeric 2",
	"Chambers of Xeric 3",
	"Chambers of Xeric 4",
	"Chambers of Xeric 5",
	"Chambers of Xeric 6",
	"Chambers of Xeric 7",
	"Chambers of Xeric 8",
	"Chambers of Xeric 9",
	"Chambers of Xeric 10",
	"Chambers of Xeric 11-15",
	"Chambers of Xeric 16-23",
	"Chambers of Xeric 24+",
	"Chambers of Xeric - Challenge mode Solo",
	"Chambers of Xeric - Challenge mode 2",
	"Chambers of Xeric - Challenge mode 3",
	"Chambers of Xeric - Challenge mode 4",
	"Chambers of Xeric - Challenge mode 5",
	"Chambers of Xeric - Challenge mode 6",
	"Chambers of Xeric - Challenge mode 7",
	"Chambers of Xeric - Challenge mode 8",
	"Chambers of Xeric - Challenge mode 9",
	"Chambers of Xeric - Challenge mode 10",
	"Theatre of Blood Room 2",
	"Theatre of Blood Room 3",
	"Theatre of Blood Room 4",
	"Theatre of Blood Room 5",
	"Theatre of Blood Overall 2",
	"Theatre of Blood Overall 3",
	"Theatre of Blood Overall 4",
	"Theatre of Blood Overall 5",
	"Theatre of Blood - Hard Room 3",
	"Theatre of Blood - Hard Room 4",
	"Theatre of Blood - Hard Room 5",
	"Theatre of Blood - Hard Overall 3",
	"Theatre of Blood - Hard Overall 4",
	"Theatre of Blood - Hard Overall 5",
	"Tombs of Amascut Challenge Solo",
	"Tombs of Amascut Challenge 2",
	"Tombs of Amascut Challenge 3",
	"Tombs of Amascut Challenge 4",
	"Tombs of Amascut Challenge 5",
	"Tombs of Amascut Challenge 6",
	"Tombs of Amascut Challenge 7",
	"Tombs of Amascut Overall Solo",
	"Tombs of Amascut Overall 2",
	"Tombs of Amascut Overall 3",
	"Tombs of Amascut Overall 4",
	"Tombs of Amascut Overall 5",
	"Tombs of Amascut Overall 6",
	"Tombs of Amascut Overall 7",
	"Tombs of Amascut Expert Challenge Solo",
	"Tombs of Amascut Expert Challenge 2",
	"Tombs of Amascut Expert Challenge 3",
	"Tombs of Amascut Expert Challenge 4",
	"Tombs of Amascut Expert Challenge 5",
	"Tombs of Amascut Expert Challenge 6",
	"Tombs of Amascut Expert Challenge 7",
	"Tombs of Amascut Expert Challenge 8",
	"Tombs of Amascut Expert Overall Solo",
	"Tombs of Amascut Expert Overall 2",
	"Tombs of Amascut Expert Overall 3",
	"Tombs of Amascut Expert Overall 4",
	"Tombs of Amascut Expert Overall 5",
	"Tombs of Amascut Expert Overall 6",
	"Tombs of Amascut Expert Overall 7",
	"Tombs of Amascut Expert Overall 8",
	"Hallowed Sepulchre",
	"Prifddinas Agility Course",
	"Duke Sucellus",
	"The Leviathan",
	"The Whisperer",
	"Vardorvis",
}

var HofSpeedCategories = map[string]struct{}{
	"TzHaar": {}, "Slayer": {}, "Nightmare": {}, "Nex": {}, "Solo Bosses": {}, "Chambers Of Xeric": {}, "Chambers Of Xeric Challenge Mode": {}, "Theatre Of Blood": {}, "Theatre Of Blood Hard Mode": {}, "Tombs Of Amascut": {}, "Tombs Of Amascut Expert": {}, "Agility": {}, "Desert Treasure 2": {},
}

var SpeedBossNameToCategory = map[string]string{
	"TzHaar Fight Cave":       "TzHaar",
	"Inferno":                 "TzHaar",
	"Alchemical Hydra":        "Slayer",
	"Grotesque Guardians":     "Slayer",
	"The Nightmare Solo":      "Nightmare",
	"The Nightmare 2":         "Nightmare",
	"The Nightmare 3":         "Nightmare",
	"The Nightmare 4":         "Nightmare",
	"The Nightmare 5":         "Nightmare",
	"The Nightmare 6+":        "Nightmare",
	"Phosani's Nightmare":     "Nightmare",
	"Nex":                     "Nex",
	"Fragment of Seren":       "Solo Bosses",
	"Galvek":                  "Solo Bosses",
	"Glough":                  "Solo Bosses",
	"The Gauntlet":            "Solo Bosses",
	"The Corrupted Gauntlet":  "Solo Bosses",
	"Hespori":                 "Solo Bosses",
	"Phantom Muspah":          "Solo Bosses",
	"Vorkath":                 "Solo Bosses",
	"Zulrah":                  "Solo Bosses",
	"Tempoross":               "Solo Bosses",
	"Chambers of Xeric Solo":  "Chambers Of Xeric",
	"Chambers of Xeric 2":     "Chambers Of Xeric",
	"Chambers of Xeric 3":     "Chambers Of Xeric",
	"Chambers of Xeric 4":     "Chambers Of Xeric",
	"Chambers of Xeric 5":     "Chambers Of Xeric",
	"Chambers of Xeric 6":     "Chambers Of Xeric",
	"Chambers of Xeric 7":     "Chambers Of Xeric",
	"Chambers of Xeric 8":     "Chambers Of Xeric",
	"Chambers of Xeric 9":     "Chambers Of Xeric",
	"Chambers of Xeric 10":    "Chambers Of Xeric",
	"Chambers of Xeric 11-15": "Chambers Of Xeric",
	"Chambers of Xeric 16-23": "Chambers Of Xeric",
	"Chambers of Xeric 24+":   "Chambers Of Xeric",
	"Chambers of Xeric - Challenge mode Solo": "Chambers Of Xeric Challenge mode",
	"Chambers of Xeric - Challenge mode 2":    "Chambers Of Xeric Challenge mode",
	"Chambers of Xeric - Challenge mode 3":    "Chambers Of Xeric Challenge mode",
	"Chambers of Xeric - Challenge mode 4":    "Chambers Of Xeric Challenge mode",
	"Chambers of Xeric - Challenge mode 5":    "Chambers Of Xeric Challenge mode",
	"Chambers of Xeric - Challenge mode 6":    "Chambers Of Xeric Challenge mode",
	"Chambers of Xeric - Challenge mode 7":    "Chambers Of Xeric Challenge mode",
	"Chambers of Xeric - Challenge mode 8":    "Chambers Of Xeric Challenge mode",
	"Chambers of Xeric - Challenge mode 9":    "Chambers Of Xeric Challenge mode",
	"Chambers of Xeric - Challenge mode 10":   "Chambers Of Xeric Challenge mode",
	"Theatre of Blood Room 2":                 "Theatre Of Blood",
	"Theatre of Blood Room 3":                 "Theatre Of Blood",
	"Theatre of Blood Room 4":                 "Theatre Of Blood",
	"Theatre of Blood Room 5":                 "Theatre Of Blood",
	"Theatre of Blood Overall 2":              "Theatre Of Blood",
	"Theatre of Blood Overall 3":              "Theatre Of Blood",
	"Theatre of Blood Overall 4":              "Theatre Of Blood",
	"Theatre of Blood Overall 5":              "Theatre Of Blood",
	"Theatre of Blood - Hard Room 3":          "Theatre Of Blood Hard Mode",
	"Theatre of Blood - Hard Room 4":          "Theatre Of Blood Hard Mode",
	"Theatre of Blood - Hard Room 5":          "Theatre Of Blood Hard Mode",
	"Theatre of Blood - Hard Overall 3":       "Theatre Of Blood Hard Mode",
	"Theatre of Blood - Hard Overall 4":       "Theatre Of Blood Hard Mode",
	"Theatre of Blood - Hard Overall 5":       "Theatre Of Blood Hard Mode",
	"Tombs of Amascut Challenge Solo":         "Tombs Of Amascut",
	"Tombs of Amascut Challenge 2":            "Tombs Of Amascut",
	"Tombs of Amascut Challenge 3":            "Tombs Of Amascut",
	"Tombs of Amascut Challenge 4":            "Tombs Of Amascut",
	"Tombs of Amascut Challenge 5":            "Tombs Of Amascut",
	"Tombs of Amascut Challenge 6":            "Tombs Of Amascut",
	"Tombs of Amascut Challenge 7":            "Tombs Of Amascut",
	"Tombs of Amascut Overall Solo":           "Tombs Of Amascut",
	"Tombs of Amascut Overall 2":              "Tombs Of Amascut",
	"Tombs of Amascut Overall 3":              "Tombs Of Amascut",
	"Tombs of Amascut Overall 4":              "Tombs Of Amascut",
	"Tombs of Amascut Overall 5":              "Tombs Of Amascut",
	"Tombs of Amascut Overall 6":              "Tombs Of Amascut",
	"Tombs of Amascut Overall 7":              "Tombs Of Amascut",
	"Tombs of Amascut Expert Challenge Solo":  "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Challenge 2":     "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Challenge 3":     "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Challenge 4":     "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Challenge 5":     "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Challenge 6":     "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Challenge 7":     "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Challenge 8":     "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Overall Solo":    "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Overall 2":       "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Overall 3":       "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Overall 4":       "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Overall 5":       "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Overall 6":       "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Overall 7":       "Tombs Of Amascut Expert",
	"Tombs of Amascut Expert Overall 8":       "Tombs Of Amascut Expert",
	"Hallowed Sepulchre":                      "Agility",
	"Prifddinas Agility Course":               "Agility",
	"Duke Sucellus":                           "Desert Treasure 2",
	"The Leviathan":                           "Desert Treasure 2",
	"The Whisperer":                           "Desert Treasure 2",
	"Vardorvis":                               "Desert Treasure 2",
}

var HofSpeedDt2 = []BossInfo{
	{BossName: "Duke Sucellus"},
	{BossName: "The Leviathan"},
	{BossName: "The Whisperer"},
	{BossName: "Vardorvis"},
}

var HofSpeedTzhaar = []BossInfo{
	{BossName: "TzHaar Fight Cave"},
	{BossName: "Inferno"},
}

var HofSpeedSlayer = []BossInfo{
	{BossName: "Alchemical Hydra"},
	{BossName: "Grotesque Guardians"},
}

var HofSpeedNightmare = []BossInfo{
	{BossName: "The Nightmare Solo"},
	{BossName: "The Nightmare 2"},
	{BossName: "The Nightmare 3"},
	{BossName: "The Nightmare 4"},
	{BossName: "The Nightmare 5"},
	{BossName: "The Nightmare 6+"},
	{BossName: "Phosani's Nightmare"},
}

var HofSpeedNex = []BossInfo{
	{BossName: "Nex", ImageLink: "https://i.imgur.com/hnw9ki8.png"},
}

var HofSpeedSolo = []BossInfo{
	{BossName: "Fragment of Seren"},
	{BossName: "Galvek"},
	{BossName: "Glough"},
	{BossName: "The Gauntlet"},
	{BossName: "The Corrupted Gauntlet"},
	{BossName: "Hespori"},
	{BossName: "Phantom Muspah"},
	{BossName: "Vorkath"},
	{BossName: "Zulrah"},
	{BossName: "Tempoross"},
}

var HofSpeedCox = []BossInfo{
	{BossName: "Chambers of Xeric Solo"},
	{BossName: "Chambers of Xeric 2"},
	{BossName: "Chambers of Xeric 3"},
	{BossName: "Chambers of Xeric 4"},
	{BossName: "Chambers of Xeric 5"},
	{BossName: "Chambers of Xeric 6"},
	{BossName: "Chambers of Xeric 7"},
	{BossName: "Chambers of Xeric 8"},
	{BossName: "Chambers of Xeric 9"},
	{BossName: "Chambers of Xeric 10"},
	{BossName: "Chambers of Xeric 11-15"},
	{BossName: "Chambers of Xeric 16-23"},
	{BossName: "Chambers of Xeric 24+"},
}

var HofSpeedCoxCm = []BossInfo{
	{BossName: "Chambers of Xeric - Challenge mode Solo"},
	{BossName: "Chambers of Xeric - Challenge mode 2"},
	{BossName: "Chambers of Xeric - Challenge mode 3"},
	{BossName: "Chambers of Xeric - Challenge mode 4"},
	{BossName: "Chambers of Xeric - Challenge mode 5"},
	{BossName: "Chambers of Xeric - Challenge mode 6"},
	{BossName: "Chambers of Xeric - Challenge mode 7"},
	{BossName: "Chambers of Xeric - Challenge mode 8"},
	{BossName: "Chambers of Xeric - Challenge mode 9"},
	{BossName: "Chambers of Xeric - Challenge mode 10"},
}

var HofSpeedTob = []BossInfo{
	{BossName: "Theatre of Blood Room 2"},
	{BossName: "Theatre of Blood Room 3"},
	{BossName: "Theatre of Blood Room 4"},
	{BossName: "Theatre of Blood Room 5"},
	{BossName: "Theatre of Blood Overall 2"},
	{BossName: "Theatre of Blood Overall 3"},
	{BossName: "Theatre of Blood Overall 4"},
	{BossName: "Theatre of Blood Overall 5"},
}

var HofSpeedTobHm = []BossInfo{
	{BossName: "Theatre of Blood - Hard Room 3"},
	{BossName: "Theatre of Blood - Hard Room 4"},
	{BossName: "Theatre of Blood - Hard Room 5"},
	{BossName: "Theatre of Blood - Hard Overall 3"},
	{BossName: "Theatre of Blood - Hard Overall 4"},
	{BossName: "Theatre of Blood - Hard Overall 5"},
}

var HofSpeedToa = []BossInfo{
	{BossName: "Tombs of Amascut Challenge Solo"},
	{BossName: "Tombs of Amascut Challenge 2"},
	{BossName: "Tombs of Amascut Challenge 3"},
	{BossName: "Tombs of Amascut Challenge 4"},
	{BossName: "Tombs of Amascut Challenge 5"},
	{BossName: "Tombs of Amascut Challenge 6"},
	{BossName: "Tombs of Amascut Challenge 7"},
	{BossName: "Tombs of Amascut Overall Solo"},
	{BossName: "Tombs of Amascut Overall 2"},
	{BossName: "Tombs of Amascut Overall 3"},
	{BossName: "Tombs of Amascut Overall 4"},
	{BossName: "Tombs of Amascut Overall 5"},
	{BossName: "Tombs of Amascut Overall 6"},
	{BossName: "Tombs of Amascut Overall 7"},
}

var HofSpeedToae = []BossInfo{
	{BossName: "Tombs of Amascut Expert Challenge Solo"},
	{BossName: "Tombs of Amascut Expert Challenge 2"},
	{BossName: "Tombs of Amascut Expert Challenge 3"},
	{BossName: "Tombs of Amascut Expert Challenge 4"},
	{BossName: "Tombs of Amascut Expert Challenge 5"},
	{BossName: "Tombs of Amascut Expert Challenge 6"},
	{BossName: "Tombs of Amascut Expert Challenge 7"},
	{BossName: "Tombs of Amascut Expert Challenge 8"},
	{BossName: "Tombs of Amascut Expert Overall Solo"},
	{BossName: "Tombs of Amascut Expert Overall 2"},
	{BossName: "Tombs of Amascut Expert Overall 3"},
	{BossName: "Tombs of Amascut Expert Overall 4"},
	{BossName: "Tombs of Amascut Expert Overall 5"},
	{BossName: "Tombs of Amascut Expert Overall 6"},
	{BossName: "Tombs of Amascut Expert Overall 7"},
	{BossName: "Tombs of Amascut Expert Overall 8"},
}

var HofSpeedAgility = []BossInfo{
	{BossName: "Hallowed Sepulchre"},
	{BossName: "Prifddinas Agility Course"},
}

var SpeedAutocompleteCategories = []*discordgo.ApplicationCommandOptionChoice{
	{
		Name:  "TzHaar",
		Value: "TzHaar",
	},
	{
		Name:  "Chambers Of Xeric",
		Value: "Chambers Of Xeric",
	},
	{
		Name:  "Chambers Of Xeric Challenge Mode",
		Value: "Chambers Of Xeric Challenge Mode",
	},
	{
		Name:  "Nightmare",
		Value: "Nightmare",
	},
	{
		Name:  "Theatre Of Blood Hard Mode",
		Value: "Theatre Of Blood Hard Mode",
	},
	{
		Name:  "Agility",
		Value: "Agility",
	},
	{
		Name:  "Tombs Of Amascut Expert",
		Value: "Tombs Of Amascut Expert",
	},
	{
		Name:  "Solo Bosses",
		Value: "Solo Bosses",
	},
	{
		Name:  "Nex",
		Value: "Nex",
	},
	{
		Name:  "Slayer",
		Value: "Slayer",
	},
	{
		Name:  "Desert Treasure 2",
		Value: "Desert Treasure 2",
	},
	{
		Name:  "Theatre Of Blood",
		Value: "Theatre Of Blood",
	},
}

// ******************************** PET ICON INFO ********************************

var PetIconInfo = map[string]string{
	"Abyssal orphan":        "<:ppOrphan:1200069435478786219>",
	"Baby mole":             "<:ppBabymole:1200069734251638906>",
	"Baron":                 "<:ppBaron:1200069431578066965>",
	"Butch":                 "<:ppButch:1200069733035294840>",
	"Callisto cub":          "<:ppCallisto:1200069730892005386>",
	"Hellpuppy":             "<:ppHellpuppy:1200068857050701864>",
	"Ikkle hydra":           "<:ppHydra:1200069430206537829>",
	"Jal-nib-rek":           "<:ppJalnibrek:1200069687338340452>",
	"Kalphite princess":     "<:ppKQ:1200068854290849823>",
	"Lil' zik":              "<:ppZik:1200069685320876132>",
	"Lil'viathan":           "<:ppLilviathan:1200069425911582801>",
	"Little nightmare":      "<:ppNightmare:1200069684456861726>",
	"Muphin":                "<:ppMuphin:1200069422803583047>",
	"Nexling":               "<:ppNexling:1200068850897657916>",
	"Noon":                  "<:ppNoon:1200068848653709312>",
	"Olmlet":                "<:ppOlmlet:1200069683395711047>",
	"Pet chaos elemental":   "<:ppChaosele:1200068842945265714>",
	"Pet dagannoth prime":   "<:ppPrime:1200069682061918330>",
	"Pet dagannoth supreme": "<:ppSupreme:1200069678823919636>",
	"Pet dagannoth rex":     "<:ppRex:1200069679931199528>",
	"Pet dark core":         "<:ppDarkcore:1200069417325822024>",
	"Pet general graardor":  "<:ppBandos:1200069676626092062>",
	"Pet k'ril tsutsaroth":  "<:ppKril:1200068839614992525>",
	"Pet kraken":            "<:ppKraken:1200069675585908827>",
	"Pet kree'arra":         "<:ppKree:1200069415274815498>",
	"Pet smoke devil":       "<:ppSmokedevil:1200068836544741426>",
	"Pet snakeling":         "<:ppSnakeling:1200069414003953786>",
	"Pet zilyana":           "<:ppZilyana:1200068832698585159>",
	"Phoenix":               "<:ppPhoenix:1200069413399961703>",
	"Prince black dragon":   "<:ppKBD:1200069411520917514>",
	"Scorpia's offspring":   "<:ppScorpia:1200069410145193985>",
	"Scurrius":              "<:ppScurry:1200069409344082011>",
	"Skotos":                "<:ppSkotos:1200068829791932467>",
	"Smolcano":              "<:ppSmolcano:1200069408370983053>",
	"Sraracha":              "<:ppSraracha:1200069406886215850>",
	"Tiny tempor":           "<:ppTinytempor:1200068826050605127>",
	"Tumeken's guardian":    "<:ppGuardian:1200068824897179759>",
	"Tzrek-jad":             "<:ppJad:1200068824402235432>",
	"Venenatis spiderling":  "<:ppVenenatis:1200068822409957477>",
	"Vet'ion jr.":           "<:ppVetion:1200068821470433402>",
	"Vorki":                 "<:ppVorki:1200068820056940725>",
	"Wisp":                  "<:ppWisp:1200068818781868214>",
	"Youngllef":             "<:ppYoungllef:1200068818270179348>",
	"Baby chinchompa":       "<:ppChin:1200071089313824778>",
	"Beaver":                "<:ppBeaver:1200071090911838249>",
	"Giant squirrel":        "<:ppSquirrel:1200071091801047080>",
	"Heron":                 "<:ppHeron:1200071092576981132>",
	"Rift guardian":         "<:ppRift:1200071093684293773>",
	"Rock golem":            "<:ppRockgolem:1200071095160668161>",
	"Rocky":                 "<:ppRocky:1200071096687394916>",
	"Tangleroot":            "<:ppTangleroot:1200071011975049256>",
	"Abyssal protector":     "<:ppAbyssalprotector:1200071003993296906>",
	"Bloodhound":            "<:ppBloodhound:1200071005855563827>",
	"Chompy chick":          "<:ppChompychick:1200071006862196836>",
	"Herbi":                 "<:ppHerbi:1200071007755587735>",
	"Lil' creator":          "<:ppLilcreator:1200071008745439252>",
	"Pet penance queen":     "<:ppPetpenancequeen:1200071011106832474>",
}

// ******************************** LOOT LOG INFO ********************************

var LootLogClanPoint = map[string]string{

	// COX
	"Dexterous prayer scroll":      "COX",
	"Arcane prayer scroll":         "COX",
	"Twisted buckler":              "COX",
	"Dragon hunter crossbow":       "COX",
	"Dinh's bulwark":               "COX",
	"Ancestral hat":                "COX",
	"Ancestral robe top":           "COX",
	"Ancestral robe bottom":        "COX",
	"Dragon claws":                 "COX",
	"Elder maul":                   "COX",
	"Kodai insignia":               "COX",
	"Twisted bow":                  "COX",
	"Twisted ancestral colour kit": "COX",
	"Metamorphic dust":             "COX",
	"Onyx":                         "COX",

	// TOB
	"Avernic defender hilt":         "TOB",
	"Ghrazi rapier":                 "TOB",
	"Sanguinesti staff":             "TOB",
	"Sanguinesti staff (uncharged)": "TOB",
	"Justiciar faceguard":           "TOB",
	"Justiciar chestguard":          "TOB",
	"Justiciar legguards":           "TOB",
	"Scythe of vitur":               "TOB",
	"Scythe of vitur (uncharged)":   "TOB",
	"Holy ornament kit":             "TOB",
	"Sanguine ornament kit":         "TOB",
	"Sanguine dust":                 "TOB",

	// TOA
	"Osmumten's fang":              "TOA",
	"Lightbearer":                  "TOA",
	"Elidinis' ward":               "TOA",
	"Masori mask":                  "TOA",
	"Masori body":                  "TOA",
	"Masori chaps":                 "TOA",
	"Tumeken's shadow":             "TOA",
	"Tumeken's shadow (uncharged)": "TOA",
	"Thread of elidinis":           "TOA",
	"Eye of the corruptor":         "TOA",
	"Jewel of the sun":             "TOA",
	"Breach of the scarab":         "TOA",

	// Clue Mega Rares
	"Gilded full helm":             "Clue Mega Rares",
	"Gilded platebody":             "Clue Mega Rares",
	"Gilded platelegs":             "Clue Mega Rares",
	"Gilded plateskirt":            "Clue Mega Rares",
	"Gilded kiteshield":            "Clue Mega Rares",
	"Gilded med helm":              "Clue Mega Rares",
	"Gilded chainbody":             "Clue Mega Rares",
	"Gilded sq shield":             "Clue Mega Rares",
	"Gilded 2h sword":              "Clue Mega Rares",
	"Gilded spear":                 "Clue Mega Rares",
	"Gilded hasta":                 "Clue Mega Rares",
	"3rd age full helmet":          "Clue Mega Rares",
	"3rd age platebody":            "Clue Mega Rares",
	"3rd age platelegs":            "Clue Mega Rares",
	"3rd age plateskirt":           "Clue Mega Rares",
	"3rd age kiteshield":           "Clue Mega Rares",
	"3rd age range coif":           "Clue Mega Rares",
	"3rd age range top":            "Clue Mega Rares",
	"3rd age range legs":           "Clue Mega Rares",
	"3rd age vambraces":            "Clue Mega Rares",
	"3rd age mage hat":             "Clue Mega Rares",
	"3rd age robe top":             "Clue Mega Rares",
	"3rd age robe":                 "Clue Mega Rares",
	"3rd age amulet":               "Clue Mega Rares",
	"Gilded scimitar":              "Clue Mega Rares",
	"Gilded boots":                 "Clue Mega Rares",
	"Gilded coif":                  "Clue Mega Rares",
	"Gilded d'hide vambraces":      "Clue Mega Rares",
	"Gilded d'hide body":           "Clue Mega Rares",
	"Gilded d'hide chaps":          "Clue Mega Rares",
	"Gilded pickaxe":               "Clue Mega Rares",
	"Gilded axe":                   "Clue Mega Rares",
	"Gilded spade":                 "Clue Mega Rares",
	"3rd age longsword":            "Clue Mega Rares",
	"3rd age wand":                 "Clue Mega Rares",
	"3rd age cloak":                "Clue Mega Rares",
	"3rd age bow":                  "Clue Mega Rares",
	"Bucket helm (g)":              "Clue Mega Rares",
	"Ring of coins":                "Clue Mega Rares",
	"3rd age druidic robe top":     "Clue Mega Rares",
	"3rd age druidic robe bottoms": "Clue Mega Rares",
	"3rd age druidic cloak":        "Clue Mega Rares",
	"3rd age druidic staff":        "Clue Mega Rares",
	"3rd age pickaxe":              "Clue Mega Rares",
	"3rd age axe":                  "Clue Mega Rares",

	// Slayer
	"Hydra's claw":          "Slayer",
	"Hydra leather":         "Slayer",
	"Primordial crystal":    "Slayer",
	"Pegasian crystal":      "Slayer",
	"Eternal crystal":       "Slayer",
	"Occult necklace":       "Slayer",
	"Dragon harpoon":        "Slayer",
	"Black tourmaline core": "Slayer",
	"Smoke battlestaff":     "Slayer",
	"Mist battlestaff":      "Slayer",
	"Dust battlestaff":      "Slayer",
	"Imbued heart":          "Slayer",
	"Eternal gem":           "Slayer",
	"Zenyte shard":          "Slayer",
	"Monkey tail":           "Slayer",
	"Heavy frame":           "Slayer",
	"Light frame":           "Slayer",
	"Ballista spring":       "Slayer",
	"Ballista limbs":        "Slayer",

	// Wilderness
	"Claws of callisto":       "Wilderness",
	"Tyrannical ring":         "Wilderness",
	"Voidwaker hilt":          "Wilderness",
	"Dragon pickaxe":          "Wilderness",
	"Skull of vet'ion":        "Wilderness",
	"Ring of the gods":        "Wilderness",
	"Voidwaker blade":         "Wilderness",
	"Fangs of venenatis":      "Wilderness",
	"Treasonous ring":         "Wilderness",
	"Voidwaker gem":           "Wilderness",
	"Amulet of avarice":       "Wilderness",
	"Craw's bow":              "Wilderness",
	"Craw's bow (u)":          "Wilderness",
	"Thammaron's sceptre":     "Wilderness",
	"Thammaron's sceptre (u)": "Wilderness",
	"Viggora's chainmace":     "Wilderness",
	"Viggora's chainmace (u)": "Wilderness",
	"Ancient crystal":         "Wilderness",
	"Ancient relic":           "Wilderness",
	"Ancient effigy":          "Wilderness",
	"Ancient medallion":       "Wilderness",
	"Ancient statuette":       "Wilderness",
	"Ancient totem":           "Wilderness",
	"Ancient emblem":          "Wilderness",
	"Dagon'hai robe top":      "Wilderness",
	"Dagon'hai hat":           "Wilderness",
	"Dagon'hai robe bottom":   "Wilderness",

	// DT2
	"Chromium ingot":             "DT2",
	"Ultor vestige":              "DT2",
	"Executioner's axe head":     "DT2",
	"Virtus mask":                "DT2",
	"Virtus robe top":            "DT2",
	"Virtus robe bottom":         "DT2",
	"Ancient blood ornament kit": "DT2",
	"Bellator vestige":           "DT2",
	"Siren's staff":              "DT2",
	"Venator vestige":            "DT2",
	"Leviathan's lure":           "DT2",
	"Magus vestige":              "DT2",
	"Eye of the duke":            "DT2",

	// Other
	"Bryophyta's essence":     "Other",
	"Hill giant club":         "Other",
	"Dragon full helm":        "Other",
	"Infernal cape":           "Other",
	"Wyvern visage":           "Other",
	"Skeletal visage":         "Other",
	"Draconic visage":         "Other",
	"Dragon warhammer":        "Other",
	"Amulet of eternal glory": "Other",
	"Evil chicken head":       "Other",
	"Evil chicken wings":      "Other",
	"Evil chicken legs":       "Other",
	"Evil chicken feet":       "Other",
	"Abyssal lantern":         "Other",
	"Abyssal needle":          "Other",
	"Abyssal green dye":       "Other",
	"Abyssal blue dye":        "Other",
	"Abyssal red dye":         "Other",

	"Scurrius' spine": "Scurrius",

	// Zulrah
	"Tanzanite mutagen": "Zulrah",
	"Magma mutagen":     "Zulrah",
	"Uncut onyx":        "Zulrah",
	"Serpentine visage": "Zulrah",
	"Magic fang":        "Zulrah",
	"Tanzanite fang":    "Zulrah",

	// Gauntlet
	"Enhanced crystal weapon seed": "Gauntlet",
	"Crystal armour seed":          "Gauntlet",

	// Godwars
	"Armadyl helmet":            "Godwars",
	"Armadyl chestplate":        "Godwars",
	"Armadyl chainskirt":        "Godwars",
	"Armadyl hilt":              "Godwars",
	"Bandos chestplate":         "Godwars",
	"Bandos tassets":            "Godwars",
	"Bandos boots":              "Godwars",
	"Bandos hilt":               "Godwars",
	"Saradomin sword":           "Godwars",
	"Saradomin's light":         "Godwars",
	"Armadyl crossbow":          "Godwars",
	"Saradomin hilt":            "Godwars",
	"Steam battlestaff":         "Godwars",
	"Zamorakian spear":          "Godwars",
	"Staff of the dead":         "Godwars",
	"Zamorak hilt":              "Godwars",
	"Zaryte vambraces":          "Godwars",
	"Nihil horn":                "Godwars",
	"Torva full helm (damaged)": "Godwars",
	"Torva platebody (damaged)": "Godwars",
	"Torva platelegs (damaged)": "Godwars",
	"Torva full helm":           "Godwars",
	"Torva platebody":           "Godwars",
	"Torva platelegs":           "Godwars",
	"Ancient hilt":              "Godwars",

	// Nightmare
	"Nightmare staff":         "Nightmare",
	"Inquisitor's great helm": "Nightmare",
	"Inquisitor's hauberk":    "Nightmare",
	"Inquisitor's plateskirt": "Nightmare",
	"Inquisitor's mace":       "Nightmare",
	"Eldritch orb":            "Nightmare",
	"Harmonised orb":          "Nightmare",
	"Volatile orb":            "Nightmare",

	// Muspah
	"Venator shard": "Muspah",

	// DKS
	"Warrior ring":   "DKS",
	"Berserker ring": "DKS",
	"Dragon axe":     "DKS",
	"Seers ring":     "DKS",
	"Archers ring":   "DKS",

	// Zalcano
	"Zalcano shard":     "Zalcano",
	"Crystal tool seed": "Zalcano",

	// Jars
	"Jar of dirt":      "Jars",
	"Jar of swamp":     "Jars",
	"Jar of sand":      "Jars",
	"Jar of souls":     "Jars",
	"Jar of miasma":    "Jars",
	"Jar of darkness":  "Jars",
	"Jar of stone":     "Jars",
	"Jar of decay":     "Jars",
	"Jar of chemicals": "Jars",
	"Jar of eyes":      "Jars",
	"Jar of dreams":    "Jars",
	"Jar of spirits":   "Jars",
	"Jar of smoke":     "Jars",
}
